services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data
    networks:
      - project-network

  python:
    container_name: py
    image: python:3.9-slim
    volumes:
      - ./scripts:/app
    working_dir: /app
    ports:
      - "8888:8888"
    entrypoint: ["bash", "init-py.sh"]
    depends_on:
      - mongodb
    networks:
      - project-network

networks:
  project-network: