#!/usr/bin/bash

set -o errexit
set -o pipefail

source .env

function up {
    docker compose up -d
}

function down {
    docker compose down
}

function db:reset {
    docker exec mongodb /bin/bash /data/init-mongo.sh
}

TIMEFORMAT=$'\nTask completed in %3lR'
time ${@}